version: '3'
services:
  flask: #Flask app
    container_name: flask-app
    build: .
    volumes:
      - .:/usr/share/flask-app/
    ports:
      - "5000:5000"
    networks:
      - esnet
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: clip_search
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./models:/usr/share/elasticsearch/models
    ports:
      - 9200:9200
    networks:
      - esnet


volumes:
  esdata:
    driver: local

networks:
  esnet:
